version: "3.7" 

services:
  db:
    container_name: "capstone-db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "list_db"
      MYSQL_USER: "default_user"
      MYSQL_PASSWORD: "1234"
    volumes:
    - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "capstone-api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
    - "8081:8081"
    depends_on:
      - db
    volumes:
    - .:/app/
networks:
  default:
volumes:
  mysql_data: