CREATE TABLE `DIM_LYRICS`
(
    id int auto_increment,
    Links varchar(200) NOT NULL, 
    DATE_ADDED CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
); 

LOAD DATA LOCAL INFILE '/input/lyrics.csv' 
INTO TABLE DIM_LYRICS 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
